// <auto-generated />
using CountersApp.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CountersApp.Migrations
{
    [DbContext(typeof(DomainContext))]
    [Migration("20200502180624_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CountersApp.Model.Counter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Counters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Key = 1,
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            Key = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 4,
                            Key = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 5,
                            Key = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 6,
                            Key = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 7,
                            Key = 2,
                            Value = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
